# Generated by Django 6.0.4 on 2026-05-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='husband',
            name='m_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='husband',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
