# Generated by Django 6.0.4 on 2026-05-17 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_husband_m_count_alter_husband_name'),
        ('women', '0009_husband_m_count'),
    ]

    operations = [
    ]
